In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel(r"F:\Machine Learning\Machine_Learning\DataModel\Financial_Sample.xlsx")

In [3]:
df.shape

(700, 16)

In [4]:
df.head(3)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,NaN,2178.0,3,15.0,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,June,2014

In [10]:
df = df.bfill()

In [11]:
df.isnull().sum()

Segment                0
Country                0
Product                0
Discount Band          0
Units Sold             0
Manufacturing Price    0
Sale Price             0
Gross Sales            0
Discounts              0
 Sales                 0
COGS                   0
Profit                 0
Date                   0
Month Number           0
Month Name             0
Year                   0
dtype: int64

In [12]:
df.isnull().sum().sum()

np.int64(0)

In [14]:
df['Sale Price'].unique()

array([ 20.,  15., 350.,  12., 125., 300.,   7.])

In [16]:
df[['Sale Price','Gross Sales']].describe()

       Sale Price   Gross Sales
count  700.000000  7.000000e+02
mean   118.331429  1.828198e+05
std    136.948113  2.542227e+05
min      7.000000  1.799000e+03
25%     12.000000  1.762500e+04
50%     20.000000  3.798000e+04
75%    300.000000  2.790250e+05
max    350.000000  1.207500e+06

In [17]:
# Standardization
# mean =0, sts =1
# z = (x-miu(mean))/sigma(std)

In [18]:
li = ['Sale Price', 'Gross Sales']

for col in li:
    df[col] = (df[col]-df[col].mean())/df[col].std()

In [19]:
df[['Sale Price','Gross Sales']].describe()

         Sale Price   Gross Sales
count  7.000000e+02  7.000000e+02
mean  -2.537653e-18  5.709718e-17
std    1.000000e+00  1.000000e+00
min   -8.129461e-01 -7.120562e-01
25%   -7.764359e-01 -6.498037e-01
50%   -7.180196e-01 -5.697361e-01
75%    1.326550e+00  3.784287e-01
max    1.691652e+00  4.030640e+00

In [20]:
df = pd.read_excel(r"F:\Machine Learning\Machine_Learning\DataModel\Financial_Sample.xlsx")

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
sc = StandardScaler()

In [29]:
output = pd.DataFrame(sc.fit_transform(df[['Sale Price','Gross Sales']]),columns=['Sale Price','Gross Sales'])

In [30]:
output.describe()

         Sale Price   Gross Sales
count  6.930000e+02  6.950000e+02
mean   4.357585e-17  1.725239e-17
std    1.000722e+00  1.000720e+00
min   -8.127232e-01 -7.155307e-01
25%   -7.760860e-01 -6.534567e-01
50%   -7.174664e-01 -5.718260e-01
75%    1.334220e+00  4.005748e-01
max    1.700592e+00  4.020295e+00

In [31]:
# Normalization
# Convert all Values  between 0 to 1
# n = (X - Xmin)/(Xmax-Xmin)

In [37]:
li = ['Sale Price','Gross Sales']
for col in li:
    df[col] = (df[col]-df[col].min())/(df[col].max() - df[col].min())

In [38]:
df[['Sale Price','Gross Sales']].describe()

       Sale Price  Gross Sales
count  693.000000   695.000000
mean     0.323367     0.151089
std      0.398168     0.211309
min      0.000000     0.000000
25%      0.014577     0.013107
50%      0.037901     0.030344
75%      0.854227     0.235673
max      1.000000     1.000000

In [39]:
df.head(2)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,0.037901,0.025355,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,0.037901,0.020420,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014

In [40]:
from sklearn.preprocessing import MinMaxScaler

In [41]:
scaler = MinMaxScaler()

In [45]:
output = pd.DataFrame(scaler.fit_transform(df[['Sale Price', 'Gross Sales']]),columns= ['Sale Price','Gross Sales'])

In [47]:
output

     Sale Price  Gross Sales
0      0.037901     0.025355
1      0.037901     0.020420
2      0.023324     0.025604
3      0.023324     0.009555
4      0.023324     0.029237
..          ...          ...
695    0.854227     0.614332
696    0.854227     0.134362
697    0.000000     0.006450
698    0.000000     0.002705
699    0.014577     0.016483

[700 rows x 2 columns]

In [48]:
output.describe()

       Sale Price  Gross Sales
count  693.000000   695.000000
mean     0.323367     0.151089
std      0.398168     0.211309
min      0.000000     0.000000
25%      0.014577     0.013107
50%      0.037901     0.030344
75%      0.854227     0.235673
max      1.000000     1.000000