In [162]:
import  pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [163]:
df = pd.read_excel(r"F:\Machine Learning\Machine_Learning\DataModel\Financial_Sample.xlsx")

In [164]:
df.shape

(700, 16)

In [165]:
df.isnull().sum()

Segment                 8
Country                11
Product                 8
Discount Band          62
Units Sold              5
Manufacturing Price     0
Sale Price              7
Gross Sales             5
Discounts               5
 Sales                  0
COGS                    0
Profit                  0
Date                    0
Month Number            0
Month Name              0
Year                    0
dtype: int64

In [166]:
df = df.bfill()

In [167]:
df.isnull().sum()

Segment                0
Country                0
Product                0
Discount Band          0
Units Sold             0
Manufacturing Price    0
Sale Price             0
Gross Sales            0
Discounts              0
 Sales                 0
COGS                   0
Profit                 0
Date                   0
Month Number           0
Month Name             0
Year                   0
dtype: int64

In [168]:
df.head(2)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,Low,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,Low,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014

In [169]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              700 non-null    str
 1   Country              700 non-null    str
 2   Product              700 non-null    str
 3   Discount Band        700 non-null    str
 4   Units Sold           700 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           700 non-null    float64
 7   Gross Sales          700 non-null    float64
 8   Discounts            700 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Date                 700 non-null    datetime64[us]
 13  Month Number         700 non-null    int64
 14  Month Name           700 non-null    str
 15  Year                 700 non-null    int64
dtypes: datetime64[us](1), float64(7), int64(3), str(5)
memory usage: 113.5 KB

In [170]:
df.columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold',
       'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts',
       ' Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name',
       'Year'],
      dtype='str')

In [171]:
df = df.drop(columns=['Date','Month Name'])

In [172]:
df.select_dtypes(include='object')

C:\Users\ROYAL WALA\AppData\Local\Temp\ipykernel_14952\676392701.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object')

              Segment                   Country    Product Discount Band
0          Government                    Canada  Carretera           Low
1          Government                   Germany  Carretera           Low
2           Midmarket                    France  Carretera           Low
3           Midmarket                   Germany  Carretera           Low
4           Midmarket                    Mexico  Carretera           Low
..                ...                       ...        ...           ...
695    Small Business                    France   Amarilla          High
696    Small Business                    Mexico   Amarilla          High
697        Government                    Mexico    Montana          High
698        Government                    Canada      Paseo          High
699  Channel Partners  United States of America        VTT          High

[700 rows x 4 columns]

In [173]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              700 non-null    str
 1   Country              700 non-null    str
 2   Product              700 non-null    str
 3   Discount Band        700 non-null    str
 4   Units Sold           700 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           700 non-null    float64
 7   Gross Sales          700 non-null    float64
 8   Discounts            700 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Month Number         700 non-null    int64
 13  Year                 700 non-null    int64
dtypes: float64(7), int64(3), str(4)
memory usage: 98.0 KB

#### Encoding all text/object type columns(OneHotEncoding,OrdinalEncoding,LabelEncoding)
##### OneHotEncoding
Canada Germany France<br>
1        0       0<br>
0        1       0<br>
0        0       1<br>

##### OrdinalEncoding
S = 0, M = 1, L = 2, XL = 3, XXL = 4 etc

#### LabelEncoding
Male = 1, Female = 0 (Randomly)

In [174]:
df.select_dtypes(include='str')

              Segment                   Country    Product Discount Band
0          Government                    Canada  Carretera           Low
1          Government                   Germany  Carretera           Low
2           Midmarket                    France  Carretera           Low
3           Midmarket                   Germany  Carretera           Low
4           Midmarket                    Mexico  Carretera           Low
..                ...                       ...        ...           ...
695    Small Business                    France   Amarilla          High
696    Small Business                    Mexico   Amarilla          High
697        Government                    Mexico    Montana          High
698        Government                    Canada      Paseo          High
699  Channel Partners  United States of America        VTT          High

[700 rows x 4 columns]

In [175]:
newdf = df.copy()

In [176]:
for col in df.select_dtypes( include='str' ).columns:
    df[col] = df[col].map( lambda var : list(df[col].unique()).index(var) )

In [177]:
list(df['Segment'].unique())

[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4)]

In [178]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              700 non-null    int64
 1   Country              700 non-null    int64
 2   Product              700 non-null    int64
 3   Discount Band        700 non-null    int64
 4   Units Sold           700 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           700 non-null    float64
 7   Gross Sales          700 non-null    float64
 8   Discounts            700 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Month Number         700 non-null    int64
 13  Year                 700 non-null    int64
dtypes: float64(7), int64(7)
memory usage: 76.7 KB

In [179]:
df.head(3)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Month Number,Year
0,0,0,0,0,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,1,2014
1,0,1,0,0,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,1,2014
2,1,2,0,0,2178.0,3,15.0,32670.0,0.0,32670.0,21780.0,10890.0,6,2014

In [180]:
df = newdf.copy()

In [181]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              700 non-null    str
 1   Country              700 non-null    str
 2   Product              700 non-null    str
 3   Discount Band        700 non-null    str
 4   Units Sold           700 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           700 non-null    float64
 7   Gross Sales          700 non-null    float64
 8   Discounts            700 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Month Number         700 non-null    int64
 13  Year                 700 non-null    int64
dtypes: float64(7), int64(3), str(4)
memory usage: 98.0 KB

In [182]:
df.head(2)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Month Number,Year
0,Government,Canada,Carretera,Low,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,1,2014
1,Government,Germany,Carretera,Low,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,1,2014

In [183]:
from sklearn.preprocessing import LabelEncoder

In [184]:
le = LabelEncoder()

In [185]:
for col in df.select_dtypes(include='str').columns:
    df[col] = le.fit_transform(df[col])

In [186]:
# OrdinalEncoder

In [187]:
df = newdf.copy()

In [188]:
df.Segment.unique()

<ArrowStringArray>
['Government', 'Midmarket', 'Channel Partners', 'Enterprise',
 'Small Business']
Length: 5, dtype: str

In [189]:
dic = {'Government':4, 'Midmarket':3, 'Channel Partners':2, 'Enterprise':0, 'Small Business':1}

In [190]:
df['Segment'] = df['Segment'].map(dic)

In [191]:
df.head(5)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Month Number,Year
0,4,Canada,Carretera,Low,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,1,2014
1,4,Germany,Carretera,Low,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,1,2014
2,3,France,Carretera,Low,2178.0,3,15.0,32670.0,0.0,32670.0,21780.0,10890.0,6,2014
3,3,Germany,Carretera,Low,888.0,3,15.0,13320.0,0.0,13320.0,8880.0,4440.0,6,2014
4,3,Mexico,Carretera,Low,2470.0,3,15.0,37050.0,0.0,37050.0,24700.0,12350.0,6,2014

In [192]:
from sklearn.preprocessing import OrdinalEncoder

In [193]:
oe = OrdinalEncoder( categories = [['United States of America', 'Germany', 'Mexico','France', 'Canada'],
                                ['Carretera', 'Montana', 'Paseo', 'Velo', 'VTT', 'Amarilla']] )

In [194]:
df.Country.unique()

<ArrowStringArray>
['Canada', 'Germany', 'France', 'Mexico', 'United States of America']
Length: 5, dtype: str

In [195]:
df.Product.unique()

<ArrowStringArray>
['Carretera', 'Montana', 'Paseo', 'Velo', 'VTT', 'Amarilla']
Length: 6, dtype: str

In [196]:
# 'United States of America', 'Germany', 'Mexico','France', 'Canada'

In [197]:
df[['Country',"Product"]] = oe.fit_transform(df[['Country','Product']])

In [198]:
df

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Month Number,Year
0,4,4.0,0.0,Low,1618.5,3,20.0,32370.0,0.00,32370.00,16185.0,16185.00,1,2014
1,4,1.0,0.0,Low,1321.0,3,20.0,26420.0,0.00,26420.00,13210.0,13210.00,1,2014
2,3,3.0,0.0,Low,2178.0,3,15.0,32670.0,0.00,32670.00,21780.0,10890.00,6,2014
3,3,1.0,0.0,Low,888.0,3,15.0,13320.0,0.00,13320.00,8880.0,4440.00,6,2014
4,3,2.0,0.0,Low,2470.0,3,15.0,37050.0,0.00,37050.00,24700.0,12350.00,6,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1,3.0,5.0,High,2475.0,260,300.0,742500.0,111375.00,631125.00,618750.0,12375.00,3,2014
696,1,2.0,5.0,High,546.0,260,300.0,163800.0,24570.00,139230.00,136500.0,2730.00,10,2014
697,4,2.0,1.0,High,1368.0,5,7.0,9576.0,1436.40,8139.60,6840.0,1299.60,2,2014
698,4,4.0,2.0,High,723.0,10,7.0,5061.0,759.15,4301.85,3615.0,686.85,4,2014
699,2,0.0,4.0,High,1806.0,250,12.0,21672.0,3250.80,18421.20,5418.0,13003.20,5,2014

In [199]:
df = newdf.copy()

In [200]:
li = list(df['Segment'].unique())
li

['Government', 'Midmarket', 'Channel Partners', 'Enterprise', 'Small Business']

In [201]:
def OneHot(li):
    for col in li:
        df[col] = df['Country'].map( lambda var : 1 if var==col else 0 )

In [202]:
OneHot( list(df['Segment'].unique()) )

In [203]:
df.head(5)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Month Number,Year,Government,Midmarket,Channel Partners,Enterprise,Small Business
0,Government,Canada,Carretera,Low,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,1,2014,0,0,0,0,0
1,Government,Germany,Carretera,Low,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,1,2014,0,0,0,0,0
2,Midmarket,France,Carretera,Low,2178.0,3,15.0,32670.0,0.0,32670.0,21780.0,10890.0,6,2014,0,0,0,0,0
3,Midmarket,Germany,Carretera,Low,888.0,3,15.0,13320.0,0.0,13320.0,8880.0,4440.0,6,2014,0,0,0,0,0
4,Midmarket,Mexico,Carretera,Low,2470.0,3,15.0,37050.0,0.0,37050.0,24700.0,12350.0,6,2014,0,0,0,0,0

In [204]:
OneHot( list(df['Country'].unique()) )

In [205]:
df.head(5)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,...,Government,Midmarket,Channel Partners,Enterprise,Small Business,Canada,Germany,France,Mexico,United States of America
0,Government,Canada,Carretera,Low,1618.5,3,20.0,32370.0,0.0,32370.0,...,0,0,0,0,0,1,0,0,0,0
1,Government,Germany,Carretera,Low,1321.0,3,20.0,26420.0,0.0,26420.0,...,0,0,0,0,0,0,1,0,0,0
2,Midmarket,France,Carretera,Low,2178.0,3,15.0,32670.0,0.0,32670.0,...,0,0,0,0,0,0,0,1,0,0
3,Midmarket,Germany,Carretera,Low,888.0,3,15.0,13320.0,0.0,13320.0,...,0,0,0,0,0,0,1,0,0,0
4,Midmarket,Mexico,Carretera,Low,2470.0,3,15.0,37050.0,0.0,37050.0,...,0,0,0,0,0,0,0,0,1,0